# Generated by Django 4.2.1 on 2023-07-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrototipShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(blank=True, to='PrototipShopApp.product'),
        ),
    ]
